apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: helsesjekk-bot
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  port: 5000
  ingresses:
    - 'https://helsesjekk-bot.intern.nav.no'
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: helsesjekk-bot
            envVarPrefix: DB

# Might not need this if socket mode works:
#  accessPolicy:
#    outbound:
#      external:
#        - host: slack.com
#        - host: api.slack.com
  liveness:
    path: /internal/is_alive
  readiness:
    path: /internal/is_ready
  envFrom:
    - secret: helsesjekk-bot-secrets
